#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts none /dev/pts
mkdir /mnt
echo hello Yair and Bryerton, this is Holguer
echo Testing LED DS3.... Att: Holguer @ Triumf...
gpio_test
sh ./drivers/gpio_test.sh
#mount -o nolock,rsize=1024 172.17.0.1:/home/vlad/test/HEAD/projects /mnt
ifconfig lo 127.0.0.1
# ifconfig eth0 172.17.0.199


